#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application directory
application=`getApplication`

if [ ! -d "0" ]; then
  cp -r $FOAM_TUTORIALS/incompressible/channelFoam/channel395/0 ./
fi

runApplication blockMesh
runApplication $application
runApplication postChannel

# ----------------------------------------------------------------- end-of-file
