#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application directory
application=`getApplication`

if [ ! -d "0" ]; then
  cp -r $FOAM_TUTORIALS/incompressible/pimpleFoam/channel395/0 ./
fi

runApplication blockMesh

#- Run serial
#runApplication $application

#- Run parallel
runApplication decomposePar -cellDist
runParallel $application 5
runApplication reconstructPar

runApplication postChannel

# ----------------------------------------------------------------- end-of-file
